-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 11, 2023 at 02:23 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `touristo_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `hot_places_country`
--

CREATE TABLE `hot_places_country` (
  `title` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `star_rating` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `hot_places_country`
--

INSERT INTO `hot_places_country` (`title`, `location`, `image`, `star_rating`) VALUES
('Kadarnath', 'India', 'https://w0.peakpx.com/wallpaper/534/827/HD-wallpaper-kedarnath-cloud-sky.jpg', '4.9'),
('Statue of Liberty', 'US', 'http://m.gettywallpapers.com/wp-content/uploads/2021/07/Statue-of-Liberty-Wallpaper.png', '4.8'),
('Singapore', 'Singapore', 'https://images.unsplash.com/photo-1565967511849-76a60a516170?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8c2luZ2Fwb3JlfGVufDB8fDB8fA%3D%3D&w=1000&q=80', '4.5');

-- --------------------------------------------------------

--
-- Table structure for table `purchased_packages`
--

CREATE TABLE `purchased_packages` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `time` varchar(255) NOT NULL,
  `date` varchar(255) NOT NULL,
  `members` varchar(255) NOT NULL,
  `transaction` varchar(255) NOT NULL,
  `price` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `purchased_packages`
--

INSERT INTO `purchased_packages` (`id`, `name`, `image`, `time`, `date`, `members`, `transaction`, `price`) VALUES
(4, 'Siddhivinayak Mandir\nMumbai, India', 'https://www.thedivineindia.com/img/siddhivinayak-temple-mumbai.jpg', '3:9 PM', 'Friday, 19 May 23', '2 Adults', '', '25200');

-- --------------------------------------------------------

--
-- Table structure for table `register_user_details`
--

CREATE TABLE `register_user_details` (
  `id` int(11) NOT NULL,
  `profile_pic` varchar(256) NOT NULL,
  `firstname` varchar(256) NOT NULL,
  `lastname` varchar(256) NOT NULL,
  `email` varchar(256) NOT NULL,
  `password` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `register_user_details`
--

INSERT INTO `register_user_details` (`id`, `profile_pic`, `firstname`, `lastname`, `email`, `password`) VALUES
(1, 'vicky.png', 'God_Mode', 'Activated', 'Vicky', 'Vicky'),
(2, 'myimage.png', 'Tony', 'Stark', 'ironman@gmail.com', 'Tony@3000'),
(3, '', 'Deepak', 'Deodhar', 'deepakdeodhar01@gmail.com', 'Devil@123'),
(4, '', 'Vicky', 'Raut', 'vraut4143@gmail.com', 'Vicky@123'),
(5, '', 'Lokesh', 'Warke', 'lokeshwarke6@gmail.com', 'Lokesh41'),
(6, '', 'Vicky', 'Raut', 'vicky11@gmail.com', '12345678');

-- --------------------------------------------------------

--
-- Table structure for table `tourist_places`
--

CREATE TABLE `tourist_places` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `latitude` double NOT NULL,
  `longitude` double NOT NULL,
  `price` int(11) NOT NULL,
  `days` int(11) NOT NULL,
  `likes` int(11) NOT NULL,
  `rating` float NOT NULL,
  `liked_status` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tourist_places`
--

INSERT INTO `tourist_places` (`id`, `name`, `city`, `country`, `image`, `description`, `latitude`, `longitude`, `price`, `days`, `likes`, `rating`, `liked_status`) VALUES
(1, 'Raigad Fort', 'Pune', 'India', 'https://www.fabhotels.com/blog/wp-content/uploads/2019/03/Rajgad-Fort.jpg', 'Raigad is a hill fort situated in Mahad, Raigad district of Maharashtra, India. It is one of the strongest fortresses on the Deccan Plateau. It was previously known as Rairee or Rairy fort. Many constructions and structures on Raigad were built by Chhatrapati Shivaji and the Chief Engineer was Hiroji Indulkar. \\n Chhatrapati Shivaji renovated this fort and made it his capital in 1674 AD. The rope-way facility is available at Raigad Fort, to reach at the fort from ground in few minutes. The fort also overlooks an artificial lake known as the \'Ganga Sagar Lake\'', 18.23483863, 73.44642294, 10000, 6, 10000, 4.8, 0),
(2, 'Siddhivinayak Mandir', 'Mumbai', 'India', 'https://www.thedivineindia.com/img/siddhivinayak-temple-mumbai.jpg', 'The Shree Siddhivinayak Ganapati Mandir is a Hindu temple dedicated to Ganesh. It is located in Prabhadevi, Mumbai, Maharashtra, India. \\n The temple has a small mandap with the shrine for Siddhi Vinayak (\"Ganesha who grants your wish\"). The wooden doors to the sanctum are carved with images of the Ashtavinayak (the eight manifestations of Ganesha in Maharashtra). The inner roof of the sanctum is plated with gold, and the central statue is of Ganesha. In the periphery, there is a Hanuman temple as well. The exterior of the temple consists of a dome which is lit up with multiple colors in the evenings and they keep changing every few hours. The statue of Shri Ganesha is located exactly under the dome. The pillars are carved out with the images of ashtvinayak.', 19.02225214, 72.82960556, 12000, 2, 12000, 4.9, 0),
(3, 'Mahakal Mandir', 'Ujjain', 'India', 'https://media.istockphoto.com/id/1161558377/photo/exterior-view-of-mahakaleshwar-temple-ujjain-madhya-pradesh-india.jpg?s=170667a&w=0&k=20&c=uJ12BxQuQNwUz1XdmLj5Jt4y8wyDCYMLrSln9tgJ6fI=', 'When did the Mahakala temple first come in existence, is difficult to tell. However, the event may be assigned to the Pre-historic period. Puranas narrate that it was first established by Prajapita Brahma. There is reference to the appointment of prince Kumarasena by king Chanda Pradyota in 6th c. BC for looking after the law and order situations of Mahakala temple. The punch-marked coins of Ujjain, belonging to 4th-3rd c. BC, bear the figure of Lord Siva on them.\n\nMahakala temple is also mentioned in several ancient Indian poetic texts. According to these texts, the temple had been very magnificent and magnanimous.Its foundation and platform were built of stones. The temple rested on the wooden pillars.There had been no sikharas on the temples prior to the Gupta period. The roofs of temples had mostly been flat.Possibly due to this fact, Kalidasa in Raghuvansam described this temple as ‘Niketana’.The palace of the king had been in the vicinity of the temple. In the early part of the Meghadutam (Purva Megha),Kalidasa gives a fascinating description of the Mahakala temple.', 22.71563507, 75.85503147, 12000, 5, 15000, 4.7, 0),
(4, 'Statue Of Unity', 'Kewadia', 'India', 'https://c0.wallpaperflare.com/preview/208/510/421/statue-patel-sardar-unity.jpg', 'The Statue of Unity is the world\'s tallest statue, with a height of 182 metres, located near Kevadia in the state of Gujarat, India. It depicts Indian statesman and independence activist Vallabhbhai Patel, who was the first deputy prime minister and home minister of independent India and an adherent of Mahatma Gandhi.', 21.8382076, 73.71910498, 13000, 4, 11000, 4.8, 0),
(5, 'Srinagar', 'Jammu & kashmir', 'India', 'https://images6.alphacoders.com/605/thumb-1920-605294.jpg', 'Silk-sunset, certain shades of white, tar on the roads, gloom beyond the oil lamp floating over the lake, ripples in the water, fog on the mirror, garden of the spring, the palace of the fairies, subject of the poems, emptiness in the eyes, absence of words, forever in ordinary things and the old roses on a breeze, where love arrives in memories of forever to liberate us into life – Srinagar! The tourist places in Srinagar offer breathtaking views and mesmerising locations to die for.', 34.08955008, 74.79437897, 18000, 5, 20000, 4.9, 0),
(6, 'Rock Garden', 'Chandigarh', 'India', 'https://i.pinimg.com/originals/a5/71/28/a57128529dbb73ef4793799772ffff11.jpg', 'By far, Chandigarh Rock Garden is the most popular one in India. Also famous as Nek Chand’s Rock Garden, this is the place where you’ll find sculptures and structures which are made using industrial and domestic waste. The region where the park is developed is quite rocky and that’s why the name', 30.75318179, 76.80914753, 1000, 2, 1000, 3.5, 0),
(7, 'Dal Lake', 'Jammu & kashmir', 'India', 'https://d2rdhxfof4qmbb.cloudfront.net/wp-content/uploads/20190312112932/Shikara-boats-on-Dal-lake-Srinagar.jpg', 'Dal Lake is one of the most famous tourist destinations in the beautiful Kashmir Valley, located in the northernmost part of India. It is known for its breathtaking views, crystal-clear waters, and picturesque surroundings. The lake is surrounded by majestic mountains and is a popular destination for boating and other water activities.', 34.11126572, 74.86830481, 1000, 1, 14000, 4, 0),
(8, 'Rann of Kutch', 'Gujarat', 'India', 'https://c1.wallpaperflare.com/preview/536/401/106/caravan-desert-safari-dune.jpg', 'The Great Rann of Kutch is a salt marsh in the Thar Desert in the Kutch District of Gujarat, India. It is about 7500 km² in area and is reputed to be one of the largest salt deserts in the world. This area has been inhabited by the Kutchi people.', 24.06023124, 70.14132739, 1100, 2, 5000, 3.5, 0),
(9, 'Mount Abu', 'Rajasthan', 'India', 'https://1.bp.blogspot.com/-cVsPQsSPRMM/VFHCFnY5_cI/AAAAAAAAB3Y/3cECCUEjTRI/s1600/aefa.jpg', 'Mount Abu is a hill station in western India’s Rajasthan state, near the Gujarat border. Set on a high rocky plateau in the Aravalli Range and surrounded by forest, it offers a relatively cool climate and views over the arid plains below. In the center of town, Nakki Lake is a popular spot for boating. Close by are the centuries-old Dilwara Temples, ornately carved from white marble and of great spiritual importance.', 24.59359972, 72.71578814, 1200, 2, 6000, 3.9, 0),
(10, 'Nanda Devi', 'Uttarakhand', 'India', 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?cs=srgb&dl=pexels-james-wheeler-417074.jpg&fm=jpg&_gl=1*1v113l0*_ga*MTE2MjA2MDAyMy4xNjgyNzk0MzU0*_ga_8JE65Q40S6*MTY4Mjc5NDM1Ni4xLjEuMTY4Mjc5NDM3Ny4wLjAuMA..', 'Nanda Devi is the second-highest mountain in India, after Kangchenjunga, and the highest located entirely within the country. It is the 23rd-highest peak in the world. Nanda Devi was considered the highest mountain in the world before computations in 1808 proved Dhaulagiri to be higher.', 30.37626816, 79.97087023, 2000, 2, 8000, 4.2, 0),
(11, 'Valley Of Flowers', 'Uttaranchal', 'India', 'https://tse4.mm.bing.net/th?id=OIP.yfYBnt0BgwotfrgJ04wGkgHaEo&pid=Api&P=0', 'Valley of Flowers National Park is an Indian national park which was established in 1982. It is located in Chamoli in the state of Uttarakhand and is known for its meadows of endemic alpine flowers and the variety of flora.', 30.70866222, 79.59283847, 1000, 1, 800, 4, 0),
(12, 'Dudhsagar Falls', 'Goa', 'India', 'https://tse3.mm.bing.net/th?id=OIP.nEkR-wxw6xwlXWTlKqHTGQHaEk&pid=Api&P=0', 'Dudhsagar Falls is a four-tiered waterfall located on the Mandovi River in the Indian state of Goa. It is 60 km from Panaji by road and is located on the Belgaum–Vasco Da Gama rail route about 46 km east of Madgaon and 80 km south of Belgaum.', 15.3146651, 74.31436091, 10000, 2, 4000, 3.9, 0),
(13, 'Matheran Hills', 'Raigad', 'India', 'https://tse1.mm.bing.net/th?id=OIP.3-CBrkUPeNs9Kw42Qa2t7wHaE8&pid=Api&P=0', 'Matheran, which means \"forest on the forehead\" (of the mountains) in Marathi, is an eco-sensitive region, declared by the Ministry of Environment, Forest and Climate Change, Government of India. It is Asia\'s only automobile-free hill station. There are many hotels and Parsi bungalows in the area.', 18.99658987, 73.27446218, 2000, 2, 5000, 3.8, 0),
(14, 'Zanskar Valley', 'Ladakh', 'India', 'https://tse2.mm.bing.net/th?id=OIP.fyodCVubyRv-Q3-wZiHg9AHaE9&pid=Api&P=0', 'Wrapped in snow capped peaks and huddled amidst two tiny alpine lakes, Zanskar is a beautiful tourist destination in the northern parts of India. It is one of the scantily inhabited Himalayan valleys blessed with immense natural scenic beauty', 33.5635266, 76.98779785, 15000, 5, 6000, 4.5, 0),
(15, 'Gulmarg', 'Jammu & kashmir', 'India', 'https://tse4.mm.bing.net/th?id=OIP.U2epJau-SwblG8K_5ICQDAHaE8&pid=Api&P=0', 'Gulmarg in Jammu and Kashmir is known to be an ideal place for skiing and is a must-visit hill station where you’ll get a chance to see the best of nature. Located in the Baramulla district, amidst the awe-striking Pir Panjal Range, Gulmarg is admired for its dreamy natural setting. If you’re looking for those beautiful places in India where you can also try some of the best adventurous activities, then you must visit the town of Gulmarg', 34.0356607, 74.3588711, 8000, 3, 5000, 4.2, 0),
(16, 'Sundarbans Mangrove', 'West Bengal', 'India', 'https://tse3.mm.bing.net/th?id=OIP.0cl51oLZ5ax_CnzYmKE2lwHaFj&pid=Api&P=0', 'For those who want to spend quality time amidst nature, one of the most amazing places in India that they can visit is Sundarbans Mangrove. This region is in the delta that has been created as a result of the unison of Meghna Rivers, Ganga, and Brahmaputra. If you happen to be in West Bengal, make sure you visit Sundarbans Mangrove without fail', 22.145876, 89.778135, 4000, 2, 2500, 4, 0),
(17, 'Ajanta Caves', 'Aurangabad', 'India', 'https://tse4.mm.bing.net/th?id=OIP.P-Eyu296eFlrU1I4TfMN-AHaEw&pid=Api&P=0', 'Ajanta Caves exemplifies one of the greatest achievements in ancient Buddhist rock-cut architecture. The artistic traditions at Ajanta present an important and rare specimen of art, architecture, painting, and socio-cultural, religious and political history of contemporary society in India.\n', 20.02613066, 75.17788075, 2000, 2, 1500, 3.4, 0),
(18, 'Leh-Ladakh', 'Ladakh', 'India', 'https://wallpapercave.com/wp/wp7029248.jpg', 'Undoubtedly, Leh – Ladakh is on every travel enthusiast’s list of famous tourist places to visit in India before they turn 30. Ride on the crazy winding roads, get stuck in the middle of nowhere, sleep with the locals, go trekking in Ladakh, and learn to be independent on the desert mountains as you undertake this adventurous journey in one of the best places in India.\n\nBest time to visit: April to mid-May and mid-September to mid-October', 34.14269478, 77.55572632, 15000, 6, 6000, 4.3, 0),
(19, 'Rishikesh', 'Uttarakhand', 'India', 'https://tse1.mm.bing.net/th?id=OIP.kd8EzWSHqvVjVDy6HMMyWQHaEK&pid=Api&P=0', 'With bursting energy and enthusiasm, the twenties is the best time to enjoy thrill and adventure, especially with your friends. Travel to the adventure capital of India, Rishikesh, and ride on the mystical but fierce fast-flowing waters of Ganges. Rishikesh is a must-visit place in India if you haven’t yet crossed the age bar.\n\nBest time to visit: September to November and February to June', 30.08737523, 78.26665946, 10000, 4, 2400, 3.8, 0),
(20, 'Jim Corbett', 'Uttarakhand', 'India', 'https://tse2.mm.bing.net/th?id=OIP.Ae4Uo9JOAWCmT1cf0EOF_gHaFj&pid=Api&P=0', 'One of the best national parks in India, Jim Corbett is famous for Indian tiger sightings. The wilderness here becomes hospitable with the luxurious jungle resorts that allow you to stay closer to nature while enjoying the best of comfort. If you’re a photography-enthusiast, Corbett will never leave you disappointed.\n\nBest time to visit: The best time to visit Jim Corbett and experiencing the safari at its best depends on the kind of experience you’re looking for. Summer is considered the best time for tiger sighting. However, November to February is the best time to visit Jim Corbett', 30.35835243, 78.01049675, 5000, 2, 3000, 3.9, 0),
(21, 'Dalhousie', 'Himachal Pradesh', 'India', 'https://tse1.mm.bing.net/th?id=OIP.uTOgfWODJP8zUIHlVPaGDwHaE8&pid=Api&P=0', 'Other than the refreshing greens, magnificent views of the mountains, gushing rivers, and the mesmerizing beauty of the nature, Dalhousie is also considered to be famous for its Victorian architecture. Once a summer capital of the British, Dalhousie is also one of the best holiday destinations in India.\n\nBest time to visit: March to June', 32.538634, 75.971225, 10000, 4, 5000, 4.2, 0),
(22, 'Hampi', 'Karnataka', 'India', 'https://tse4.mm.bing.net/th?id=OIP.2-gnCvbTIZa0-6xhEsizzwHaE9&pid=Api&P=0', 'Hampi’s world heritage site is amongst the must-visit tourist places in India. Known for its old monumental and architectural beauty, Hampi place will dispose of you to a world of aesthetics. PS: Don’t plan a trip to Hampi in summers.', 15.334973, 76.460291, 8000, 3, 6500, 4.1, 0),
(23, 'Mathura', 'Uttar Pradesh', 'India', 'https://travelsparadise.in/wp-content/uploads/2021/05/1472715092_prem-mandir-min.jpg', 'Allow your spirit to soak in the raas-leela of Vrindavan. The place that celebrates Krishna’s living philosophy. The festival is ecstatic, to say the least and celebration of colours here would the best you’d experience ever in your life.', 27.488904, 77.676503, 15000, 3, 15000, 4.5, 0),
(24, 'Ooty Hill Station', 'Tamil Nadu', 'India', 'http://www.doddabetta.com/wp-content/uploads/2018/04/ootyhill.jpg', 'Much famed as Udhagamandalam amongst the locals, Ooty is one of the most popular and frequented holiday destinations in India. Home to mighty rock mountains, the thrilling Nilgiri Mountain Railway, refreshing gardens, and dangerous hair-pin bends, Ooty never fails to charm the travelers with its magic.', 11.406751, 76.692422, 5000, 2, 8000, 3.9, 0),
(25, 'Mahabaleshwar', 'Maharashtra', 'India', 'https://tse3.mm.bing.net/th?id=OIP.DqRuDkq-PoDo5KZh-K9mBAHaE8&pid=Api&P=0', 'Considered to be one of the most picturesque tourist destinations in India, Mahabaleshwar is one of the refreshing retreats that Western Ghats has to offer to the travellers. From the cascading waterfalls to the lush green ghats, your visit to Mahabaleshwar will be wrapped in mist and guided by the clouds.', 17.931048, 73.64822, 8000, 3, 6000, 4, 0),
(26, 'Happy Valley', 'West Bengal', 'India', 'https://www.trawell.in/admin/images/upload/646902927Darjeeling_Happy_Valley_Tea_Estate_Main.jpg', 'Considered to be the most frequented tourist destinations in India, Darjeeling is a common name in the houses of those who love chai more than anything else. Renowned across the world for its varieties of tea, Darjeeling effortlessly charms everyone with its refreshing greens and soothing blues.', 27.051829, 88.26341, 2000, 3, 1000, 3.1, 0),
(27, 'Nainital', 'Uttarakhand', 'India', 'https://tse1.mm.bing.net/th?id=OIP.sftS2hKnTK4aQ94ElPXsMwHaE-&pid=Api&P=0', 'Located at an elevation of 2,000m, Nainital is a resort town in the Kumaon Hills of Uttarakhand. The place gets its name from a lake called ‘Naini Lake’ around which the whole town is established. The lake is popular for boating scenes and has an ancient Devi Hindu Temple on its northern shore. Nainital has a pleasant climate throughout the year. Surrounded by many snow-capped hills and having a number of lakes in its boundary, there are a plethora of beautiful sights that you can enjoy here.', 29.39156, 79.455708, 9000, 4, 6000, 3.2, 0),
(28, 'Kalpitty Island', 'Lakshadeep', 'India', 'https://tse1.mm.bing.net/th?id=OIP.WfbK-qRvEf69AaZXZixP9gHaEK&pid=Api&P=0', 'The Indian islands, Lakshadweep is an archipelago (group) of 36 islands which consists of 12 atolls, 3 reefs and 5 submerged banks. This is one of the most popular tropical island destinations and the smallest Union Territory in India. Only some islands of this archipelago are inhabited and just a few are open to the visitors. But the pristine beaches, azure waters, beach resorts and water adventure sports make Lakshadweep a travel-must. Kavaratti is one of the most developed islands and is popular for beautifully decorated mosques.', 10.813574, 72.166432, 10000, 3, 5000, 4, 0),
(29, 'Chopta', 'Uttarakhand', 'India', 'https://images.thrillophilia.com/image/upload/s--_o6ThtKz--/c_fill,f_auto,fl_strip_profile,h_800,q_auto,w_1300/v1/images/photos/000/127/731/original/1525089652_shutterstock_283593458.jpg.jpg?1525089652', 'Chopta is a small but significant region in Uttarakhand. The place is covered with alpine and grassy meadows and forests making this a peaceful getaway into the laps of nature. The Chopta Valley is surrounded by many mighty mountain peaks that create a breathtaking backdrop. A part of the Kedarnath Wildlife Sanctuary, Chopta is also a base for trekking to Tungnath, one of the Panch Kedar. The best way to explore this place is through trekking and visiting the local tourist spots on the way.', 30.346429, 79.048534, 4000, 2, 3000, 4, 0),
(30, 'Spiti Valley', 'Himachal Pradesh', 'India', 'https://spitiadventure.com/wp-content/uploads/2020/05/places-to-visit-in-Spiti-Valley-12.jpg', 'Located at an altitude of 12,500 feet above the sea level, Spiti Valley is one of the most sought after travel destinations in Himachal Pradesh. ‘Spiti’ means ‘the middle land’. The region is characterized by winding roads, wide valleys, arid deserts and snow-capped mountains. The clear and open sky in Spiti will leave you spellbound while you stargaze in the night. The valley has some of the oldest monasteries that you that add to the charm of this mystic region. Spiti is also a trekking hotspot popular among the adventure enthusiasts.', 32.248155, 78.035322, 5000, 3, 5999, 4.3, 0),
(31, 'Gokarna', 'Uttarakhand', 'India', 'https://tse2.mm.bing.net/th?id=OIP.i25egvW0V1_XI52_yI4rxAHaE8&pid=Api&P=0', 'Gokarna is a town on the Arabian Sea, located in Karnataka. It is a Hindu pilgrimage destination, with a number of sacred sites including the Mahabaleshwara Temple and Koti Teertha. Gokarna is often metaphorized as a ‘crowd-less Goa’. The places has many amazing beaches where you can spend some time relaxing in peace.', 14.547292, 74.320083, 10000, 4, 3900, 4.1, 0),
(32, 'Orchha Fort', 'Madhya Pradesh', 'India', 'https://tse2.mm.bing.net/th?id=OIP.4U8SZ_fxyrAWsMEtF8z6-wHaEZ&pid=Api&P=0', 'Located in the Tikamgarh district of Madhya Pradesh, Orchha is a town known for its grand historical structures including palaces, temples and forts. Set on the banks of Betwa river, the medieval architectural heritage of this place attracts tourists from around the world. Orchha is also popular for its frescos and classical murals paintings. There are many beautiful temples in this town. Chaturbhuj Temple is one of the most popular temple which was built by the queen of Orchha, Ganeshi Bai.', 25.371159, 78.6312477, 5000, 2, 3500, 3.9, 0),
(33, 'Pahalgam', 'Jammu & kashmir', 'India', 'https://media.cntraveller.in/wp-content/uploads/2018/06/Getaways-Lead-866x487.jpg', 'A hill station in Jammu And Kashmir, Pahalgam is a nature’s paradise. Small houses, saffron farms, green fields, and lush valleys with the mighty Himalayan ranges forming the backdrop, Pahalgam is one of the most picturesque destinations of North India. The Overa Aru Wildlife Sanctuary located here is a habitat for many Himalayan species of fauna and flora including the musk deer and brown bears. There are many fast-flowing rivers in Pahalgam which makes it a perfect river rafting site too.', 34.015952, 75.313872, 25000, 4, 15000, 4, 0),
(34, 'Landsdowne', 'Uttarakhand', 'India', 'http://eragenx.com/wp-content/uploads/2016/08/Lansdowne.jpg', 'hill stations near delhi cover picture', 29.839515, 78.689168, 20000, 4, 2000, 4, 0),
(35, 'Joshinath', 'Uttarakhand', 'India', 'https://travelphantom.com/wp-content/uploads/2021/03/Snow-fall-in-Joshimath.jpg', 'Joshimath, in northern the tip of the Indian subcontinent on the Himalayas, is one of the major tourist attractions in Northern India. Joshimath is one of the most beautiful tourist attractions in the state of Uttarakhand, which attracts tourists who are always in pursuit of a peaceful vacation. While one can visit the hills throughout the year, the best time to visit Joshimath is during summers, as it offers excellent relief from the sizzling summer heat', 30.551954, 79.565181, 12000, 4, 1500, 3.9, 0),
(36, 'Tawang', 'Shannan', 'India', 'https://tse2.mm.bing.net/th?id=OIP.uUupAODgmCYtZZskcxb9JAHaE5&pid=Api&P=0', 'Tawang’s landscape is adorned with massive rocky yet green mountains, group of Buddhist monasteries, and ethnicity of Monpa hamlets. Its iconic 17th-century monastery has always been a boss at stealing hearts. The warm hospitality and pleasant weather are two primary reasons Tawang is counted among one of the best places to visit in India before you turn 30.', 27.553124, 91.678848, 15000, 2, 2000, 4.1, 0),
(37, 'Manikaran', 'Himachal Pradesh', 'India', 'https://i.pinimg.com/originals/b9/c2/4b/b9c24b1355aa1d82177d17d9a0c45c0b.jpg', 'A pilgrimage centre for Hindus and Sikhs, Manikaran is most popular for its hot springs. With religious tourists pouring-in in large numbers, it has become quite crowded. Manikaran is located 90 km from Manali. Descend on this area of worship and seek the blessings of Gods. It is considered one of the best places to visit in India before you turn 30.', 32.026794, 77.350986, 25000, 5, 5000, 5, 0),
(38, 'Madikeri', 'Karnataka', 'India', 'https://tse3.mm.bing.net/th?id=OIP.jjWYLYiyoG5--eUeHbZNVQHaEj&pid=Api&P=0', 'Madikeri is one of the most visited hill stations in Karnataka. Encircled by the Western Ghats, it is known for its scenic beauty, misty hills, wildlife, local cuisines, and coffee plantations. Staying in the lap of nature is nothing less than stepping into heaven. You will have a blast here. We suggest you take this trip solo. You can also take this trip with friends or family', 12.424722, 75.737991, 20000, 5, 6000, 4.2, 0),
(39, 'Ranikhet', 'Uttarakhand', 'India', 'https://i.pinimg.com/originals/b2/69/6a/b2696a1e4f05ab04ec25bc8ac7dbc455.jpg', 'A lovely cantonment hill-town in Uttarakhand, Ranikhet is also known as Queen’s Meadow. It is believed to be the resident of Queen Padmini of Kumaon. Revered shrines, a 9-hole golf course, rich orchards, and breathtaking nature in Ranikhet are the reasons why it is one of the best summer tourist places in India. It is considered as one of the most offbeat places to visit in India before you turn 30.', 29.643498, 79.434182, 15000, 4, 4000, 4.3, 0),
(40, 'Kausani', 'Uttarakhand', 'India', 'https://www.weekendthrill.com/wp-content/uploads/2016/07/Kausani-compressed.jpg', 'Located in the Bageshwar district of Uttarakhand, Kausani is a perfect getaway away from the hustle and bustle of the city. Kausani is famous for its 300 km wide scenic views of some of the tallest peaks of the Himalayas like Nanda Devi and Panchachuli. Kausani weather is mild and hovers around 9 to 26 degrees. It is considered as one of the best places to visit in India before you turn 30', 29.843754, 79.603382, 21000, 3, 4999, 4.5, 0),
(41, 'Agumbe', 'Karnataka', 'India', 'https://tse1.mm.bing.net/th?id=OIP.X4yzLk6nBAdj4YOxGeIeJQHaE8&pid=Api&P=0', 'Known for its scenic beauty and biodiversity, Agumbe is a settlement situated in Karnataka. The lush rainforest also has many popular waterfalls such as Bakarna, Onake Abbi, and Jogi Gundi falls. There is a sunset viewpoint as well where you can enjoy the evening. If you are a wildlife enthusiast, you will be excited to know that there are some wild species that you can spot here like leopards and tigers.', 13.475251, 75.120863, 5000, 1, 9000, 4.2, 0),
(42, 'Munnar', 'Kerala', 'India', 'https://tse2.mm.bing.net/th?id=OIP.lP4lC85PdMp0LQDMF26weQHaFj&pid=Api&P=0', 'Munnar is a place which is known for its beautiful tea gardens, lakes and pretty hill stations. Located at the Western Ghats, this is one of the best places to visit in India with friends and family. This beautiful hill station is the commercial centre for some of the biggest tea estates of the world. In addition to this the hill station is considered to be one of the most protected areas where som', 10.088376, 77.059527, 18000, 5, 8000, 4.6, 0),
(43, 'Gangtok', 'Sikkim', 'India', 'https://tse3.mm.bing.net/th?id=OIP.ai5dcH1JarBpOZncFh26TAHaFb&pid=Api&P=0', 'With the spectacular view of the Mt. Kanchenjunga in the backdrop and the alluring clouds covering the peaks, Gangtok appears to be an intact painted picture. This beautiful hill station is located amidst the mountains and clouds. And alongside that it is also a base for many trekkers who hike up to the Himalayan ranges. It is one of the most beautiful hill stations which has a blend of traditions and urbanisation.', 27.332317, 88.60849, 21000, 1, 6000, 5.1, 0),
(44, 'Kanha National Park', 'Madhya Pradesh', 'India', 'https://tse2.mm.bing.net/th?id=OIP.hJS4XjSX5pm9vzNIdSjdRwHaFj&pid=Api&P=0', 'Situated at the central region of Madhya Pradesh, the Kanha National Park is quite a famous place to visit. This is known as one of the best parks in Asia which shelters around 22 species of large mammals. Alongside that this place is also one of the well-known tiger reserves. Established in 1955, people visit this park to enjoy an exciting wildlife safari.', 22.146112, 80.660124, 8000, 4, 3000, 5, 0),
(45, 'Mussoorie', 'Uttarakhand', 'India', 'https://tse1.mm.bing.net/th?id=OIP.tlGXtIQTvaXND730NYz-KQHaDm&pid=Api&P=0', 'Mussoorie is considered to be one of the best places to visit in India with friends in Uttarakhand. Resting at the foothills of the Garhwal Himalayan ranges, this place is also known as the “Queen of Hills”. Located at a height of 7000 feet above sea level, this place has so much to offer beyond the pleasant climate and natural beauty of the hills.', 30.46048, 78.062707, 25000, 3, 5000, 4.3, 0),
(46, 'Vaishno Devi', 'Jammu & kashmir', 'India', 'https://2.bp.blogspot.com/-rRf0qzw3-sY/Vveus4WnRdI/AAAAAAAADII/j2kimj5oDUAsBUrLzvGErw9LOcY10zHqQ/s1600/Vaishno%2BDevi%2Bharstuff%2B1.jpg', 'Vaishno Devi is a holy cave that holds major importance in India and every year experience a vast number of devotees coming there. This place is located close to the Trikuta Hills, which is 13 kms away from Katra. This Holy Shrine was incepted in 1986 and since then the devotees come to this place to seek the blessings. This is one of the most famous places in India which must be visited at least once in a lifetime.', 33.031032, 74.947685, 20000, 2, 8000, 4.5, 0),
(47, 'Alleppey', 'Kerala', 'India', 'https://tse3.mm.bing.net/th?id=OIP.FLzKCW4YxOF4KkPCJBKVQQHaEY&pid=Api&P=0', 'Also called Alappuzha, Alleppey is a beautiful city located in the South Indian State of Kerala and surrounded by the Laccadive Sea. Enclosed by the green paddy fields and the surreal avifauna, Alleppey is a place which is worth visiting. Counted as one of the dream places to visit in India, Alleppey is a home to backwaters, beaches and beautiful lagoons.', 9.518159, 76.366965, 25000, 3, 7000, 4.2, 0),
(48, 'Lonavala', 'Maharashtra', 'India', 'https://tse2.mm.bing.net/th?id=OIP.Zr34Dk_0bJtpn2nqI2QI3AHaE4&pid=Api&P=0', 'Another popular tourist places to visit in India is Lonavala. It is the most visited hill station in Maharashtra and is a popular destination for camping, trekking and other thrilling sports. It allures tourists with its beauty. Surrounding by gorgeous waterfalls and forests, it is a must-visit place for all nature lovers.', 18.770486, 73.359528, 22000, 4, 9000, 4, 0),
(49, 'Coonoor', 'Tamil Nadu', 'India', 'https://www.tajhotels.com/content/dam/thrp/destinations/Coonoor/16x7intro/Intro.jpg/_jcr_content/renditions/cq5dam.web.1280.1280.jpeg', 'Coonoor is a serene hill station located in Tamil Nadu that is known for its tea estates. Being surrounded by Nilgiri Hills, the place attracts nature lovers from across the country. Roses, eucalyptus trees, and rhododendrons are in abundance, especially at Sim’s Park. The steam Nilgiri Mountain Railway passes through Coonoor and offers the spellbinding views of lush green Nilgiri Hills.', 11.353692, 76.796573, 22000, 3, 5000, 4, 0),
(50, 'Varkala', 'Kerala', 'India', 'https://tse3.mm.bing.net/th?id=OIP.WZrVSVdC-ALs5iU6k8VI8gHaDw&pid=Api&P=0', 'Coonoor is a serene hill station located in Tamil Nadu that is known for its tea estates. Being surrounded by Nilgiri Hills, the place attracts nature lovers from across the country. Roses, eucalyptus trees, and rhododendrons are in abundance, especially at Sim’s Park. The steam Nilgiri Mountain Railway passes through Coonoor and offers the spellbinding views of lush green Nilgiri Hills.', 8.73866, 76.719168, 5000, 1, 6000, 4.2, 0),
(51, 'Manali', 'Himachal Pradesh', 'India', 'https://i.pinimg.com/originals/84/ed/16/84ed165239f3e217d6ffb72a266d15a4.jpg', 'Manali is a town, near Kullu town in Kullu district in the Indian state of Himachal Pradesh. It is situated in the northern end of the Kullu Valley, formed by the Beas River.\n', 32.24331797, 77.18952279, 25000, 4, 25000, 4.9, 0),
(52, 'Varanasi', 'Uttar Pradesh', 'India', 'https://wallpapercave.com/wp/wp6612900.jpg', 'Situated on the banks of River Ganga in Uttar Pradesh, the holy city of Varanasi or Banaras is counted among the most sacred places in India. The city is known for some of the most revered temples and Ghats in the country and is frequented by devotees and tourists from across the world. Varanasi, one of the oldest cities in the world, is also popular as the home of Lord Shiva and Goddess Parvati. It is believed that taking a dip in the Ganges can wash away all your sins. The bustling city is popular for its museums, authentic Banarasi food, Banarasi sarees and handicrafts as well', 25.32073965, 82.97256499, 20000, 5, 9000, 4.9, 0),
(53, 'Amritsar', 'Punjab', 'India', 'https://tse2.mm.bing.net/th?id=OIP.C_CEWQmKg9W-2gNPbnoPnQHaE8&pid=Api&P=0', 'Steeped in history and spirituality, Amritsar is one of the most-visited cities in the state of Punjab. It is home to the famous Golden Temple or Sri Harmandir Sahib and is frequented by devout Sikhs and tourists from across the globe. The city also gives a nudge to your patriotic side with sites like Jallianwala Bagh and Wagah Border. The charm of Amritsar is such that tourists visit the place time and again to pay their respects at Golden Temple and watch the mesmerising Wagah-Attari Border ceremony held at the India-Pakistan border.', 31.63556374, 74.87320594, 5000, 4, 12000, 4.6, 0),
(54, 'Andaman and Nicobar Islands', 'Andaman and Nicobar', 'India', 'https://wallpapercave.com/wp/wp5296535.jpg', 'For the longest time, a trip to the Andamans meant picking between homestays or the only premium boutique hotel on the island. That’s changed in the past few years, with resorts like Taj Exotica Resort & Spa and Jalakara. The most recent entrant to the mix is Tilar Siro, a CGH Earth outpost in Havelock Island (now, Swaraj Dweep). The 25-key property is breezy, green and immersive. You can learn about the island’s history and food, take scuba diving courses and enjoy guided walks through the dense rainforests. There’s a lot to do beyond Havelock, including sea safaris at Cinque Island and kayaking expeditions with stargazing thrown in. Take a day trip to Barren Island to visit India’s only active volcano or take a ferry to Little Andaman Island for pristine beaches and lagoons. Arundhati Ail', 11.95079335, 92.10513176, 30000, 5, 15000, 4.8, 0),
(55, 'Maldives', 'Republic of Maldives', 'India', 'https://tse3.mm.bing.net/th?id=OIP.X4P4tA0E5w28Fy9LxHwhBQHaHo&pid=Api&P=0', 'The Maldives is a tropical holiday destination in the Indian Ocean. The stunning islands are very relaxed and offer an experience which can best be described as a getaway on a desert island but with high quality accommodation, spectacular food, excellent service and an extensive range of activities.', -0.74492608, 73.14626835, 45500, 4, 20000, 4.8, 0),
(56, 'Nohkalikai Falls', 'Cherrapunji', 'India', 'https://tse1.mm.bing.net/th?id=OIP.RrDGwnLPNJn_xqX2EiHvdwHaFj&pid=Api&P=0', 'Its height is 340 metres (1,115 ft).The waterfall is located in the Indian state of Meghalaya, near Cherapunji, one of the wettest places on Earth. Nohkalikai Falls are fed by the rainwater collected on the summit of a comparatively small plateau and decrease in power during the dry season, from December to February.', 25.2755786, 91.68626431, 15000, 3, 15000, 4.2, 0),
(57, 'Drang Drung Glacier', 'Near Kargil', 'India', 'https://tse2.mm.bing.net/th?id=OIP.u_rLNzTgVwtTP1qNWZENIQHaEK&pid=Api&P=0', 'The Drang Drung Glacier is a mountain glacier on the Kargil-Zanskar Road near the Pensi La mountain pass. With a maximum length of 23 kilometres and an average elevation of 4,780 metres, the Drang-Drung Glacier is the biggest in Ladakh other than the Siachen Glacier in the Karakoram Range.', 33.74659884, 76.29087583, 20000, 4, 5000, 4.2, 0),
(58, 'Khajjiar', 'Himachal Pradesh', 'India', 'https://tse1.mm.bing.net/th?id=OIP.Xxth-9raHeaDQ7z45uV1nwHaEK&pid=Api&P=0', 'ven though this happened back in 1992, the attraction of the place has not diminished even a bit. Khajjiar is a small hill station located in Chamba district, and is a famous tourist attraction in Himachal Pradesh. You should visit this quaint and dreamy place to simply celebrate its existence.', 32.54652609, 76.05108005, 0, 5, 9000, 4, 0),
(59, 'Sand Dunes', 'Jaisalmer', 'India', 'https://tse1.mm.bing.net/th?id=OIP.TV3-Q3IsugnqmWOLgMOAcgHaE8&pid=Api&P=0', 'sand dune, any accumulation of sand grains shaped into a mound or ridge by the wind under the influence of gravity. Sand dunes are comparable to other forms that appear when a fluid moves over a loose bed, such as subaqueous “dunes” on the beds of rivers and tidal estuaries and sand waves on the continental shelves beneath shallow seas.', 24.73281882, 69.48541685, 12000, 4, 10000, 4, 0),
(60, 'Munsiyari', 'Uttrakhand', 'India', 'https://tse4.mm.bing.net/th?id=OIP.mng2G0vALnF0IA_7FzNK4gHaFj&pid=Api&P=0', 'Nestled amidst the snow-clad ranges of Pithoragarh, Munsiyari is a quaint hamlet that remains snowbound for most of the year. Offering pristine landscape bordered by towering Himalayan peaks, Munsiyari is like nature\'s amphitheatre, where every morning and evening, you can enjoy spell-binding views of the sun rising from and setting behind the jagged peaks. From here, you can get stunning panoramic views of the sun-kissed Panchachuli peaks. Munsiyari is also the base for trekking expeditions to Ralam and Milam Glaciers and the Nanda Devi Peak. Munsiyari is surrounded by rolling greenery, the closest being the Munsiyari', 30.0718358, 80.23678172, 25000, 3, 12000, 4.2, 0),
(61, 'Chilka Lake', 'Chilka Lake', 'India', 'https://tse1.mm.bing.net/th?id=OIP.HNZYYcEziFqOkSy3wJwcZQHaFj&pid=Api&P=0', 'Located at the mouth of the Daya River, Chilika Lake is the largest coastal lagoon in India and also the second largest saltwater lagoon in the world after the New Caledonian barrier reef in New Caledonia. The lake is studded with small islands including the most charming Honeymoon Island and the Breakfast Island.', 19.93664955, 85.12793065, 25000, 4, 50000, 5, 0),
(62, 'Caves', 'Meghalaya', 'India', 'https://tse2.mm.bing.net/th?id=OIP.UTIObatFDpzrx3s7R_PR1AHaEK&pid=Api&P=0', 'The Caves of Meghalaya comprise a large number of caves in the Jaintia, Khasi Hills, and Garo Hills districts in the Indian state of Meghalaya, and are amongst the longest cav', 25.70309742, 90.66687802, 25000, 4, 12000, 3.9, 0),
(63, 'Palolem Beach', 'Goa', 'India', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Palolem_beach.jpg', 'Palolem Beach is located at 15°00′36″N 74°01′24″E, within 2.5 kilometres of the market town of Chaudi in South Goa, and about 40 minutes from Margao, the district headquarters of South Goa . Other neighbouring beaches in South Goa include Agonda Beach and Patnem Beach. The nearest airport is Dabolim Airport, around 67 km away.', 15.01041327, 74.02193357, 25000, 3, 9000, 4, 0),
(64, 'Nilgiri Hills', 'Tamil Nadu', 'India', 'https://tse1.mm.bing.net/th?id=OIP.CtBy5SeZi5ECQ_z6aIUd0QHaFj&pid=Api&P=0', 'Welcome to Nilgiris, one of the oldest mountain ranges, located at the tri-junction of Tamil Nadu, Kerala and Karnataka. Nilgiris is a part of the Western Ghats. Ooty the “Queen of Hill Stations”, Coonoor 19 kms from Ooty and Kotagiri 31 kms from Ooty, are the three hill stations of this district..', 11.37514542, 76.76193661, 25000, 3, 9000, 4, 0),
(65, 'Bhedaghat', 'Madhya Pradesh', 'India', 'https://tse1.mm.bing.net/th?id=OIP.ycFs7aprMOsoRZCJR2ttVgHaFT&pid=Api&P=0', 'It is situated by the side of river Narmada and is approximately 20 km from Jabalpur city. Bhedaghat is famous for the high marble rocks making a valley through which river Narmada flows. The place also has a beautiful waterfall, known as Dhuandhar Falls (literally meaning a stream of smoke, because of its appearance).', 23.13097245, 79.80072317, 54000, 4, 10000, 3, 0),
(66, 'Lonar Crater', 'Maharashtra', 'India', 'https://tse1.mm.bing.net/th?id=OIP.PnOHUcmkaGkMXqL1SXIVrQHaEj&pid=Api&P=0', 'The Lonar crater is the world\'s only salt water lake in basaltic rock, believed to have been caused by a meteorite hitting Earth around 52,000 years ago. It is surrounded by forests with a large variety of birds, particularly peacocks, owls, red-wattled lapwings and ducks . Lonar has its own ecological system.', 19.97669624, 76.50857009, 25000, 3, 9000, 4, 0),
(67, 'Gandikota Canyon', 'Andhra Pradesh', 'India', 'https://tse4.mm.bing.net/th?id=OIP.dJIoyIQi0XSw5F2SFM35lwHaEK&pid=Api&P=0', 'Ask Your Question Endearingly known as the ‘Grand Canyon of India’, Gandikota is a small and quaint village in the Kadapa district of Andhra Pradesh. Flanked by River Pennar on the right side, the village is famous for the spectacular gorges formed by the river cutting through Erramala Hills.', 14.81558632, 78.28219133, 45000, 4, 12000, 3, 0),
(68, 'Kudremukh Grassland', 'Karnataka', 'India', 'https://tse2.mm.bing.net/th?id=OIP.zmQT6XQeCIzhQidrJLmWewHaEK&pid=Api&P=0', 'This is also called as Samseparvath historically as it used to access from Samse village. Kudremukh is nestled in the heart of the western ghats in Chikkamagaluru district. It comes under Kudremukh National Park which is the second-largest wildlife protected area in the western ghats.', 13.22321378, 75.25043602, 25000, 3, 52220, 4, 0),
(69, 'Kaas Plateau', 'Maharashtra', 'India', 'https://tse4.mm.bing.net/th?id=OIP.-OI_w7fMIr0byN4nD-4YsAHaE6&pid=Api&P=0', 'Ceropegia vincifolia (locally known as Kandilpushpa/Kandil kharchudi) Kaas plateau is a plateau located near Satara. It is situated high hill plateaus and grasslands turns into a \'valley of flowers\' during monsoon season, particularly from August to early October. Kaas Plateau has more than 150 or more types of flowers, shrubs and grasses.', 17.72631698, 73.81660213, 35000, 4, 12000, 3, 0),
(70, 'Chembra Peak', 'Kerala', 'India', 'https://tse2.mm.bing.net/th?id=OIP.ARpuJ_I4-_ID0KhSQkz9tgHaEh&pid=Api&P=0', 'Chembra Peak (Chembra Mala) is a mountain in the state of Kerala, India, with an elevation of 2,100 m (6,890 ft) above sea level.[2] The highest peak in the Wayanad hills and one of the highest peaks in the Western Ghats, adjoining the Nilgiri Hills and Vellarimala, it is located in the Wayanad district of Kerala, near the town of Meppadi and 8 km (5 mi) south of Kalpetta.', 11.51251125, 76.08921641, 2000, 3, 82222, 5, 0),
(71, 'Emerald Lake', 'Ooty', 'India', 'https://tse3.mm.bing.net/th?id=OIP.a6AbgrJBMxiih8DP8qiofAHaEh&pid=Api&P=0', '/ 51.444; -116.531 Emerald Lake is a freshwater lake located in Yoho National Park, British Columbia, Canada. [1] Yoho National Park is one of the 4 contiguous National Parks in the heart of Canada\'s Rocky Mountains, along the boundary of British Columbia and Alberta Provinces, the other Parks are Kootenay, Jasper, and Banff.', 11.33118821, 76.61834115, 25000, 4, 15000, 4, 0),
(72, 'Srinagar', 'Jammu & kashmir', 'India', 'https://tse3.mm.bing.net/th?id=OIP.mBi3pgZMmHtbmlScJcL8NQHaFj&pid=Api&P=0', 'Srinagar (English: /ˈsriːnəɡər/ (listen), Kashmiri pronunciation: [siriːnagar]) is the largest city and the summer capital of Jammu and Kashmir, India. It lies in the Kashmir Valley on the banks of the Jhelum River, a tributary of the Indus, and Dal and Anchar lakes. The city is known for its natural environment, gardens, waterfronts and houseboats. It is known for traditional Kashmiri handicrafts like the Kashmir shawl (made of pashmina and cashmere wool), and also dried fruits.[11][12] It is the 31st-most populous city in India, the northernmost city in India to have over one million people,[13] and the second-largest metropolitan area in the Himalayas (after Kathmandu, Nepal).', 34.08329466, 74.78613922, 54000, 3, 8000, 3, 0),
(73, 'Shimla', 'Jammu & kashmir', 'India', 'https://tse3.mm.bing.net/th?id=OIP.HDP6fnmhqynlAVKIhxhIqAHaEK&pid=Api&P=0', 'Lakkar Bazaar, a market extending off the Ridge, sells souvenirs and crafts made of wood. Tatta Pani, 55 kilometres (34.2 mi) from the main city, is the name of hot sulphur springs that are believed to have medicinal value located on the banks of the River Satluj. Shimla is also home to South Asia\'s only natural ice skating rink.', 31.10482002, 77.17961954, 25000, 4, 80000, 4, 0),
(74, 'Tirthan Valley', 'Uttarakhand', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2017/05/317.jpg', 'Striking a perfect balance between peace and adventure, Tirthan Valley is one tourist place in India that has off-lately gained much popularity among travellers across the world. Located in the district of Kullu, Tirthan has something to offer to everyone.', 31.64219181, 77.43655334, 20000, 5, 9000, 3, 0),
(75, 'Udaipur', 'Rajasthan', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2017/09/110.jpg', 'Udaipur is called the Venice of the East, but the different Rajasthani hues of the city surely make it stand out. The City of Lakes has to be on your list of best places to travel in India. Even though Udaipur boasts of having some of the most gracious luxury heritage hotels, it will embrace you with all the warmth even if you’re looking for budget stays. Boating, trekking, sightseeing are just some activities you may indulge during your visit to the city.', 24.58578752, 73.71001738, 15000, 4, 45000, 4, 0),
(76, 'Jaisalmer', 'Rajasthan', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2015/10/Patwon-Ki-Haveli.jpg', 'The Golden City of Rajasthan, Jaisalmer is surely one of the best cities to visit in India. This part of Rajasthan lies in the Thar Desert region, exhibiting the magic of velvet sand dunes meshed with the ever-colourful culture of the state. Jaisalmer is where you can spend your time indulging in exciting activities such as dune bashing, camel safari, and desert camping. Yes! Desert camping in Jaisalmer makes for an experiential stay, with all the luxury you could wish for.', 26.91551259, 70.9093203, 15000, 5, 62000, 4, 0),
(77, 'Jodhpur', 'Rajasthan', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2017/01/Untitled-design-4.jpg', 'Jodhpur, or the Blue City of Rajasthan, will lure you with its massive hill fort called the Mehrangarh Fort. Right from this point, you get to behold the city’s landscape washed in blue. The interiors will transfer you back to the olden era. The cobbled pavements of this city exhibit the essence of Rajasthan in all its glory.', 26.24077718, 73.01920911, 15000, 3, 8000, 4, 0),
(78, 'Prashar Lake', 'Rajasthan', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2017/05/616.jpg', 'Located at a distance of about 49 kilometers towards the north of Mandi district, Prashar Lake is one of the rising trekking hotspots in Himachal Pradesh. Offering scintillating views of the Dhauladhar range, it is indeed one of the beautiful places in India.', 31.75428269, 77.10098466, 25000, 4, 9000, 4, 0),
(79, 'Dhanaulti', 'Rajasthan', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2017/05/814.jpg', 'Located at an elevation of about 2200 meters with Mussourie and Chamba as its bordering cities, Dhanaulti has off-lately emerged as one of the most offbeat destinations in India. For those who like to experience life at their own pace be it fast or slow, this is the perfect place to be.', 30.40678526, 78.23453136, 25000, 3, 50000, 4, 0),
(80, 'Tirupati', 'Andhra Pradesh', 'India', 'https://assets.traveltriangle.com/blog/wp-content/uploads/2019/12/Stay-At-The-Serene-Guesthouse-At-ISKCON-Tirupati-16_dec.jpg', 'Located at the Chittoor district of Andhra Pradesh, Tirupati is famous for its majestic Venkateshwara Temple which is one of the most famous pilgrimage centres in India. Tirupati is believed to be one of the oldest cities which is mentioned in the ancient scriptures. And alongside that, people can see devotees rushing to the temple to take one glimpse of the 8-feet tall idol of Lord Venkateshwara.', 13.62697151, 79.41758619, 23000, 4, 8000, 4, 0),
(81, 'Khajuraho', 'Madhya Pradesh', 'India', 'https://img.traveltriangle.com/blog/wp-content/uploads/2020/10/Khajuraho-400x229.jpg', 'A UNESCO World Heritage Site situated in Madhya Pradesh. The site is popular across the world for its marvelous temples adorned with sensuous & attractive carvings. The architecture of this place aims to depict the erotic forms of love, the illustrations on the wall portray passion in the most aesthetic & appealing ways. Built during 950 to 1050 AD the carvings show a paradox with the conventional Indian ideals that leave the visitors spellbound.', 24.83260718, 79.9214376, 12456, 2, 6000, 4, 0),
(82, 'Singapore', 'Singapore', 'Singapore', 'https://images.pexels.com/photos/777059/pexels-photo-777059.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Singapore is a country that celebrates colorful culture. Take the best budget foreign trips to Singapore in 2023 and make loads of memories. A tiny yet modern country offers great bargains and is a wise way to spend money on a vacation.', 1.352083, 103.819839, 42, 4, 10000, 4.4, 0),
(83, 'Malaysia', 'Malaysia', 'Malaysia', 'https://images.pexels.com/photos/22804/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'There are numerous exciting things to do in Malaysia that will make you have the best time here! Think of Malaysia for budget foreign trips and you shall begin to imagine turquoise waters, stunning beaches and pleasant climate.', 4.210484, 101.975769, 40, 5, 20000, 4.3, 0),
(84, 'Thailand', 'Thailand', 'Thailand', 'https://images.pexels.com/photos/3732494/pexels-photo-3732494.jpeg', 'Topping the charts is the world-renowned destination – Thailand. Indulge in its beaches, mountains, culture, food, and more. And the best part is, it is one of the cheap international destinations from India that fits just within the budget for all. It is one of the most cheap foreign trips from India. From adventure enthusiasts to leisure seekers, Thailand offers one of those international trips under 30k from India that is for every kind of traveler.', 15.870032, 100.992538, 35, 2, 50000, 4, 0),
(85, 'Indonesia', 'Indonesia', 'Indonesia', 'https://images.pexels.com/photos/12726407/pexels-photo-12726407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Rich in cultural heritage, visit Indonesia for its encouraging natural beauty bounded by much more! If you are looking for international trips under 1 lakh then Indonesia is one destination that you can surely consider! It is really is perfect for a low budget foreign trip. You could also plan your trip around the time of festivals in Indonesia for a unique cultural experience. Indonesia happens to be one of the best and cheap foreign trips from India without a visa. So travel to this beautiful destination of luxury and tranquility without any hassles!', -0.789275, 113.921326, 45, 4, 10000, 3.9, 0),
(86, 'Seychelles Islands', 'Seychelles Islands', 'Seychelles Islands', 'https://images.pexels.com/photos/11652831/pexels-photo-11652831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Seychelles Islands would totally fit your requirement if you want to plan a a low-budget foreign tour. Nested amidst the sparkling Indian Ocean, this African nation is essentially an archipelago formed by over 100 islands. Famed for its boundless natural beauty and picture-perfect range of beaches, it is an ideal place to take budget international trips with your family or better half.', -4.6522226, 55.43881063, 40, 6, 20000, 5, 0),
(87, 'Qatar', 'Qatar', 'Qatar', 'https://images.pexels.com/photos/3703813/pexels-photo-3703813.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The stunning beauty of the Persian Gulf, Qatar is a one of the most prismatic tourist destination amongst the Arab countries. If you still haven’t explored this place then make sure that you plan your next budget international trip to Qatar this year. There are plenty of places to visit in Doha for a wonderful vacation. Qatar also happens to be one of the offbeat places to take an international trip that is not heavy on your pockets! It may not be on of the cheap international destinations but you can surely travel on a budget.', 25.312811, 51.19111, 45, 4, 300000, 3.4, 0);
INSERT INTO `tourist_places` (`id`, `name`, `city`, `country`, `image`, `description`, `latitude`, `longitude`, `price`, `days`, `likes`, `rating`, `liked_status`) VALUES
(88, 'United Arab Emirates', 'United Arab Emirates', 'United Arab Emirates', 'https://images.pexels.com/photos/2406731/pexels-photo-2406731.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Another stunning beauty of the Arab word is the United Arab Emirates with Dubai as its most precious tourist jewel. A hub for international tourists, UAE is found in the bucket lists of several travelers. If you are one of them then this is the year when you can plan a budget international trip and explore the UAE. This land of Sheikhs hides attractions that never fail to inspire awe and blankets experiences that are nothing less than Royal! Dubai is indeed one of the cheapest countries to visit from India.', 23.841924, 54.114509, 50, 5, 50000, 4.1, 0),
(89, 'Hong Kong', 'Hong Kong', 'Hong Kong', 'https://images.pexels.com/photos/2861883/pexels-photo-2861883.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The former British colony perched on the shore of South China Sea offers plenty of bargains despite being famous for its glitz lifestyle. Head here for a groovy and electrifying holiday experience. Hong Kong is one of the best places when thinking of cheap international destinations from India so make sure that you explore it this year if you still haven’t.', 22.319852, 114.169326, 40, 5, 400000, 4.2, 0),
(90, 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'https://images.pexels.com/photos/739409/pexels-photo-739409.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Sri Lanka is one of the most cheap foreign trips from India. Famous for being the best backpacking destination, it is home to landscapes and culture which is much like India. Visit this home away from home that solves the purpose for those looking forward to cheap foreign trips from India. It is one of the world’s cheapest countries to travel from India. With the fragrance of tea plantations encircling the atmosphere, lush green foliage covering the floors, and locals serving the mouth-watering dishes, Sri Lanka is a destination that takes away the breath of travelers!', 7.595999, 80.699873, 35, 6, 60000, 4.4, 0),
(91, 'Cambodia', 'Cambodia', 'Cambodia', 'https://images.pexels.com/photos/1534057/pexels-photo-1534057.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Cambodia is one of the most beautiful yet cheapest international destinations. The enchanting form of cultural heritage, the country of Cambodia will leave you wanting for more with its panoramic and rustic beauty. It is one of the most cheap foreign trips from India.', 12.715269, 104.924154, 25, 2, 10000, 4.5, 0),
(92, 'Vietnam', 'Vietnam', 'Vietnam', 'https://images.pexels.com/photos/1660996/pexels-photo-1660996.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Vietnam is indeed one of the best places for budget international trips. Shaped like the letter “S”, lying on the eastern part of Indo-Chinese peninsula is Vietnam. In the country you will find timeless charm, and a flavor of another Asian culture which is why it is one of the best places to visit in March outside India.', 14.498164, 0, 40, 6, 20000, 3.7, 0),
(93, 'Bhutan', 'Bhutan', 'Bhutan', 'https://images.pexels.com/photos/4525420/pexels-photo-4525420.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The scenic country also called as the ‘land of the Thunder Dragons’ or the ‘Druk Yul’, offers pristine untouched natural wonders.This year is full of long weekends and Bhutan is one of the best among the various cheap international destinations from India. Head to on a trip to the Shangri La of Himalayas. It is one of the most cheap foreign trips from India.', 27.409976, 90.425551, 35, 7, 13333, 4.8, 0),
(94, 'Nepal', 'Nepal', 'Nepal', 'https://images.pexels.com/photos/1531660/pexels-photo-1531660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'An ideal holiday destination for all types of traveler, surrounded by lofty peaks and scenic landscapes lays Nepal. It is a beautiful country which is every traveler’s delight and makes way for the globetrotters to embark on one of the best budget international trips under 30k. It is the world’s cheapest countries to travel from India.', 0, 83.947283, 25, 8, 55555, 5, 0),
(95, 'Turkey', 'Turkey', 'Turkey', 'https://images.pexels.com/photos/2668314/pexels-photo-2668314.jpeg', 'You think of Turkey and the instant obvious is Istanbul which also makes it the highest famed tourist spots in the world. It is the world’s cheapest foreign tour from India. If you are looking for best budget international trips from india then you can surely plan a trip to Turkey!', 38.892407, 35.437122, 30, 9, 70005, 3.9, 0),
(96, 'Kenya', 'Kenya', 'Kenya', 'https://images.pexels.com/photos/1670732/pexels-photo-1670732.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Another destination that offers awesome low budget international trip is Kenya. The first thing that pops up when you think about Kenya is the exorbitant African wildlife and safaris. Moreover, the destination is a perfect pick for wildlife photography.', 0.487078, 37.887836, 30, 4, 600500, 5, 0),
(97, 'Egypt', 'Egypt', 'Egypt', 'https://images.pexels.com/photos/5609738/pexels-photo-5609738.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Egypt – the mum-mummy-ia place could offer a vacation for a lifetime. If you still haven’t expored Egypt then grab this chance to plan of the best budget international trips. Whether you are a history buff or an explorer, you would definitely enjoy a few days here.', 26.495772, 29.903917, 40, 3, 255555, 4.9, 0),
(98, 'South Korea', 'South Korea', 'South Korea', 'https://images.pexels.com/photos/2246789/pexels-photo-2246789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'South Korea is another place where you can take budget trips abroad from India. It will impress you with its lush green and hilly countryside, studded with cherry trees, along with the ancient Buddhist temples. The fusion of coastal fishing villages, sub-tropical islands and high-tech cities including the capital, Seoul, together contribute to an amazing low-budget international tour experience.', 36.474609, 127.707337, 40, 6, 233333, 4.8, 0),
(99, 'Myanmar', 'Myanmar', 'Myanmar', 'https://images.pexels.com/photos/3560161/pexels-photo-3560161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Also known as Burma, the country of Myanmar embraces multi ethnicity and culture. Further the scenic beauty of the country will leave you spell bound. So, make sure that you tick of this destination from your bucket list by planning of the budget-friendly international trips.', 21.331922, 96.489866, 35, 5, 455555, 4.6, 0),
(100, 'China', 'China', 'China', 'https://images.pexels.com/photos/189833/pexels-photo-189833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'A giant tourist attracting magnet of the Asian continent is China! It boasts of being the 3rd highest visited country in the world. Plan a foreign tour in low budget and explore China the way you want. Indulge in Chinese delicacies, visit world-class attractions, enjoy a sneak-peek into it’s culture while making the most of your vacation', 35.86166, 104.195396, 40, 2, 100000, 4.2, 0),
(101, 'Taiwan', 'Taiwan', 'Taiwan', 'https://images.pexels.com/photos/981147/pexels-photo-981147.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Also known as “Formosa”, the stunning beauty of Taiwan will take you through varied landscapes of artistic buildings, shimmering skyscrapers, luxury resorts, high-rising mountains, and beautiful Chinese temples. Explore all these places by planning one of the best budget international trips this year.', 23.697809, 120.960518, 40, 4, 80000, 4.7, 0),
(102, 'Lebanon', 'Lebanon', 'Lebanon', 'https://images.pexels.com/photos/3610377/pexels-photo-3610377.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'With the title of being one of the most ancient countries in the world, Lebanon represents rich history and diversity in its culture. It is one of the best cheap international trips from India. If you still haven’t explored Lebanon then this your chance to plan a budget international trip with your friends or family.', 33.854721, 35.862286, 45, 3, 90000, 4.6, 0),
(103, 'Sultanate Of Oman', 'Sultanate Of Oman', 'Sultanate Of Oman', 'https://images.pexels.com/photos/10599258/pexels-photo-10599258.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Sultanate of Oman is the cheapest foreign trip from India. Another jewel in the Persian Gulf is, Oman with Muscat at its capital which is famed for being the second best city in the world. It is one of the best budget international trips under 30K.', 23.613541, 58.594109, 30, 5, 70000, 3.7, 0),
(104, 'Russia', 'Russia', 'Russia', 'https://images.pexels.com/photos/753339/pexels-photo-753339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Russia is among the most stunning as well as tourist-friendly destinations in the world. It definitely qualifies for budget friendly international trips from India. And what’s more, its diverse cultures, varied traditions, mouth-watering cuisine makes it an indispensable part of your travel wishlist! In fact, it’s one of the highest visited places in Europe owing to its boundless natural beauty. Make sure that you cover Russia in this year as it is one of the best places to plan cheap international trips', 61.52401, 105.318756, 45, 6, 600000, 3.8, 0),
(105, 'Jordan', 'Jordan', 'Jordan', 'https://images.pexels.com/photos/3214958/pexels-photo-3214958.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Jordan isn’t just about open-air museums, ancient ruins, and great skylines. Its happening nightlife and gorgeous beaches also attract travelers from far and wide and the fact that it is one of the cheapest countries to visit from India makes it even more lucrative. The delicious cuisine, warm and friendly people, and unique activities make Jordan an adventure-packed and destination for wanderers steeped in history. The government is developing Jordan as an important center for tourism competing with its neighbors, and it has started contributing tremendously in its economy. So, include Jordan in your list of bugdet international trips and tick off this destination this year.', 30.5852, 36.2384, 30, 4, 705044, 3.9, 1),
(106, 'Paraguay', 'Paraguay', 'South America', 'https://images.pexels.com/photos/90597/pexels-photo-90597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'A less-popular country in the South American continent, Paraguay is what every adventurer dreams of. It is an unconventional choice for budget international trips from India. To give you the exact vibes of an offbeat holiday, this place boasts of a mix of conventional and modern living styles – a place where you’ll see carts and Mercedez standing together. That’s right! With a subtropical forest land like Atlantic in one corner and dense vegetation in Chaco on the other corner, you simply cannot go wrong with this place! Plan a budget foreign trip to Paraguay and explore this place with your loved one, family or friends.', -9.605854, -57.121479, 45, 3, 700000, 4.9, 0),
(107, 'Laos', 'Laos', 'Laos', 'https://images.pexels.com/photos/1385474/pexels-photo-1385474.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'If your wanderlust is giving you an itch but your pocket cannot afford any, then there is still one place where you could take a trip without losing much. Plan a low budget international trip to Laos and have an amazing backpacking experience in this South East Asian country. In case your geography is weak, then you should know that Laos shares its borders with Vietnam and Cambodia. It is one of the most stunning yet cheap countries to visit from India.', 19.475655, 102.494562, 30, 3, 70500, 4.4, 0),
(108, 'Japan', 'Japan', 'Japan', 'https://images.pexels.com/photos/3408353/pexels-photo-3408353.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'If you are looking for international honeymoon destinations in budget, you could fly to Japan. It is not only beautiful but also culturally rich country where you would get to experience a variety of things. It is the best foreign trip in low budget if you can manage.', 36.26483, 138.157189, 65, 2, 600000, 4.3, 0),
(109, 'Greece', 'Greece', 'Greece', 'https://images.pexels.com/photos/161815/santorini-oia-greece-water-161815.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Take a low budget foreign trip to the island of Greece and enjoy Mediterranean landscapes. Greece is one of the most romantic places with its enchanting scenery and what not. If you plan your holiday carefully, you can definitely manage a low budget international trip to Greece.', 39.358723, 22.482662, 50, 6, 200000, 4, 0),
(110, 'Philippines', 'Philippines', 'Philippines', 'https://images.pexels.com/photos/1076240/pexels-photo-1076240.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The list of budget international trips couldn’t be complete without talking about Philippines. Emerald rice fields, water buffaloes, beautiful beaches, graffiti walls and a place where even the fuming volcanoes look pretty, Philippines is made of dreams. You can indulge in canoeing, mountain biking and many other adventure activities here. The place can make you have the cheapest foreign trip from India.', 12.410718, 122.966876, 50, 3, 355550, 3.9, 0),
(111, 'Nicaragua', 'Nicaragua', 'Nicaragua', 'https://images.pexels.com/photos/3822541/pexels-photo-3822541.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'As weird as the name might sound, this is one of the best cheap international trips you can take. Imagine a place that is beautifully tucked between two gorgeous countries with a marvellous coastline, that’s Nicargua. Nestled between Costa Rica and Honduras, Nicargua is best desscribed as an unending terrain of lakes and beaches and volcanoes. The place is known for the cheapest foreign tour packages from India.', 12.783198, -85.072632, 42, 4, 10000, 5, 0),
(112, 'Bangladesh', 'Bangladesh', 'Bangladesh', 'https://images.pexels.com/photos/122107/pexels-photo-122107.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Planning a cheapest international trip from India? Now we know Bangladesh is not the “go to” destination for everyone but nevertheless its beautiful. If you are looking for places to visit outside India then Bangladesh is worth considering. It is a perfect combination of beautiful and cheap international holidays.', 24.144149, 90.251581, 40, 3, 20000, 3.4, 0),
(113, 'Bolivia', 'Bolivia', 'Bolivia', 'https://images.pexels.com/photos/3290069/pexels-photo-3290069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Well, imagine a destination where natural wonders and which is also one of the cheapest countries to visit from India! Well, that’s Bolivia for you. One of the offbeat countries in South America. If you ask what is the most unique and special things about this country then it is its versatility. We are still wondering how one small country can house mountains, desert and rainforests and even a glass smooth lake.', -16.957261, -64.691949, 35, 9, 50000, 4.1, 0),
(114, 'The Great Barrier Reef', 'Australia', 'Australia', 'https://images.pexels.com/photos/6465339/pexels-photo-6465339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Great Barrier Reef is one of the undisputed best vacation spots for anyone who wants the opportunity to glimpse one of the most incredible marvels of nature.', -18.00000488962461, 146.833324, 45, 6, 10000, 4.2, 0),
(115, 'Plitvice Lakes', 'Croatia', 'Croatia', 'https://images.pexels.com/photos/14319765/pexels-photo-14319765.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Plitvice Lakes can be found on Croatia’s Adriatic Sea coast, just lingering on the border between Zadar and the nation’s capital, Zagreb.', 44.86539, 15.582017, 40, 7, 20000, 4.4, 0),
(116, 'Victoria Falls', 'Zambia/Zimbabwe', 'Zambia/Zimbabwe', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/e0/bb/d4/an-angels-view.jpg?w=800&h=-1&s=1', 'Victoria Falls is one of the earth’s largest waterfalls, reaching a majestic 355 feet in height and spanning across an entire mile.', -17.93179, -17.93179, 45, 4, 300000, 4.5, 0),
(117, 'Grand Canyon National Park', 'USA', 'USA', 'https://images.pexels.com/photos/4341879/pexels-photo-4341879.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'If you like traveling at all, the Grand Canyon National Park in Arizona is one of the best places to visit.', 36.099781, -112.112587, 50, 5, 50000, 3.7, 0),
(118, 'Bora Bora', 'French Polynesia', 'French Polynesia', 'https://images.pexels.com/photos/1188473/pexels-photo-1188473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Bora Bora is an island paradise isolated from much of the world, in the middle of the South Pacific ocean.', -16.507827, -151.742092, 40, 2, 400000, 4.8, 0),
(119, 'Petra', 'Jordan', 'Jordan', 'https://images.pexels.com/photos/720254/pexels-photo-720254.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Petra is an awe-inspiring archaeological site that holds so much history and breathtaking majesty that it is easily one of the best vacation spots in the world.', 30.328439, 35.444359, 35, 3, 60000, 5, 0),
(120, 'Arashiyama Bamboo Grove', 'Japan', 'Japan', 'https://images.pexels.com/photos/6160161/pexels-photo-6160161.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Arashiyama Bamboo Grove is among the best places to travel in the already attraction-packed nation of Japan.', 35.01682015, 135.671334, 25, 6, 10000, 3.9, 0),
(121, 'Stonehenge', 'England', 'England', 'https://images.pexels.com/photos/1448136/pexels-photo-1448136.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Stonehenge is such a mysterious location, which is why it is one of the best places to visit in the world.', 51.178869, -1.825958, 40, 4, 20000, 5, 0),
(122, 'Amalfi Coast', 'Italy', 'Italy', 'https://images.pexels.com/photos/3225528/pexels-photo-3225528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Whether you’re looking for some calm relaxation, you’re itching for some fresh seafood, or you desire something more adventurous, Amalfi Coast is one of the best vacation spots you can hope for.', 40.633342, 14.602942, 35, 6, 13333, 4.9, 0),
(123, 'Machu Picchu', 'Peru', 'Peru', 'https://images.pexels.com/photos/2929906/pexels-photo-2929906.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Machu Picchu may have been famous for a long time, but it’s one of the more recently discovered old archaeological ruins, and it’s definitely one of the top best places to travel in the world.', -13.226707, -72.497257, 25, 4, 55555, 4.8, 0),
(124, 'Niagara Falls', 'Canada/USA', 'Canada/USA', 'https://images.pexels.com/photos/1486902/pexels-photo-1486902.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Niagara Falls, positioned on the border between America and Canada, is a once-in-a-lifetime type of trip that you won’t regret.', 43.08683, -79.088002, 30, 6, 70005, 4.6, 0),
(125, 'Cappadocia', 'Turkey', 'Turkey', 'https://images.pexels.com/photos/3889704/pexels-photo-3889704.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Cappadocia is likely one of the most intriguing vacation spots in the world.This is because of its fascinating, unique, and borderline bizarre natural structures known as fairy chimneys.', 38.729163, 35.292247, 30, 5, 600500, 4.2, 0),
(126, 'Neuschwanstein Castle', 'Germany', 'Germany', 'https://images.pexels.com/photos/234311/pexels-photo-234311.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'You may feel like Neuschwanstein Castle looks familiar.That’s because the famed Cinderella’s Castle building, located in Disney World, is heavily inspired by and modeled after this incredible, opulent palace.', 47.55757611, 10.7497983, 40, 7, 255555, 4.7, 0),
(127, 'Marble Caves', 'Argentina/Chile', 'Argentina/Chile', 'https://images.pexels.com/photos/14437116/pexels-photo-14437116.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Marble Caves are among the best places to visit if you are a fan of unreal sights that you can barely believe exist.', -46.658473, -72.628423, 40, 8, 233333, 4.6, 0),
(128, 'Cliffs of Moher', 'Ireland', 'Ireland', 'https://images.pexels.com/photos/2382681/pexels-photo-2382681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Cliffs of Moher span 14 kilometers across County Clare, Ireland, and it’s a prime location for untamed, natural beauty.', 52.97257, -9.42938, 35, 9, 455555, 3.7, 0),
(129, 'Salar de Uyuni', 'Bolivia', 'Bolivia', 'https://images.pexels.com/photos/13575545/pexels-photo-13575545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Salar de Uyuni makes for an unusual trip, but it’s still one of the best vacations you might ever go on', -20.460369, -66.825832, 40, 6, 100000, 3.8, 0),
(130, 'Blue Lagoon', 'Iceland', 'Iceland', 'https://images.pexels.com/photos/346972/pexels-photo-346972.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'If you’re a sucker for a good soak in a hot spring, the Blue Lagoon is one of the best places to travel.', 63.879083, -22.444951, 40, 4, 80000, 3.9, 0),
(131, 'Torres Del Paine National Park', 'Chile', 'Chile', 'https://images.pexels.com/photos/66092/pexels-photo-66092.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Torres Del Paine National Park is located in the southernmost region of the Andes, and it is full of diverse natural sights to enjoy.', -50.942357, -73.406718, 45, 3, 90000, 4.9, 0),
(132, 'Socotra', 'Yemen', 'Yemen', 'https://images.pexels.com/photos/11201283/pexels-photo-11201283.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Socotra is one of those unusual places that is more bizarre than normal, but that just makes it one of the best vacation spots for nature-lovers.It is an archipelago that hosts countless towering dragon’s blood trees, which fan upwards like an umbrella or a giant, branch-filled mushroom.', 12.446015, 53.827567, 30, 6, 70000, 4.4, 0),
(133, 'Okavango Delta', 'Botswana', 'Botswana', 'https://images.pexels.com/photos/1629803/pexels-photo-1629803.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Okavango Delta is one of those travel destinations that have to be experienced at least once in a lifetime.On either side, you’ll be able to spot incredibly diverse wildlife, ranging from predators like cheetahs to herd mammals like elephants, zebras, rhinos, and buffalos.', -19.020217, 22.75767, 45, 5, 600000, 4.3, 0),
(134, 'The Colosseum', 'Rome', 'Rome', 'https://images.pexels.com/photos/1701595/pexels-photo-1701595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Colosseum is easily one of the world’s top travel destinations.Known originally as the Flavian Amphitheatre, it originally served as an arena for entertainment through gladiator fights and other similar events.', 41.889531, 12.492403, 30, 4, 705044, 4, 1),
(135, 'Moraine Lake', 'Canada', 'Canada', 'https://images.pexels.com/photos/2827843/pexels-photo-2827843.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Moraine Lake is often referred to as the earth’s most stunning and picturesque lake.It sits within the Banff National Park, where it is nestled in a valley between ten hill and mountain peaks.', 51.323241, -116.186058, 45, 3, 700000, 3.9, 0),
(136, 'Avenue of the Baobabs', 'Madagascar', 'Madagascar', 'https://images.pexels.com/photos/4153968/pexels-photo-4153968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Avenue of the Baobabs, like the name suggests, is home to incredible baobabs that reach up into the sky at 100-foot heights.Each of these ancient trees appears surreal and almost alien-like in aesthetic as if they leaped right out of the pages of The Little Prince, where they are so whimsically featured.', -20.250501, 44.419877, 30, 4, 70500, 5, 0),
(137, 'Mount Kilimanjaro', 'Tanzania', 'Tanzania', 'https://images.pexels.com/photos/12844388/pexels-photo-12844388.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Mount Kilimanjaro is the highest peak in all of Africa, and, amazingly, it isn’t connected to a mountain range of any kind.It hits 19,000 feet in height and is surrounded by flat expanses, so it truly stands out and serves as a noticeable and breathtaking landmark.', -3.067682, 37.356357, 65, 3, 600000, 3.4, 0),
(138, 'Raja Ampat Islands', 'Indonesia', 'Indonesia', 'https://images.pexels.com/photos/2583852/pexels-photo-2583852.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Raja Ampat Islands aren’t just a few specific places – they span 1,500 different small islands that take up 29,000 square miles of ocean, and each one is biodiverse and highly unique.If you’re up for resplendent nature to feast your eyes on, these islands will be among the best vacations you’ll ever take.', -1.004585, 130.659026, 50, 4, 200000, 4.1, 0),
(139, 'Northern Lake Baikal', 'Russia', 'Russia', 'https://images.pexels.com/photos/1694083/pexels-photo-1694083.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Northern Lake Baikal is an extremely large freshwater lake – the biggest on the planet!If you visit when temperatures are at great lows, you’ll be in for an aesthetically pleasing treat.', 53.47144, 108.092692, 50, 3, 355550, 4.2, 0),
(140, 'Reed Flute Caves', 'China', 'China', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Reed_flute_cave.jpg', 'China’s Reed Flute Caves are among the nation’s best places to travel.The cave system runs for about 240 meters and it has been open for public viewing for more than a thousand years!', 25.374127, 110.120684, 42, 4, 10000, 4.4, 0),
(141, 'Geiranger Fjord', 'Norway', 'Norway', 'https://images.pexels.com/photos/12671393/pexels-photo-12671393.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'We already know that Norway is easily in the top best places to visit in the world if you want to see grand, dazzling fjords of all kinds.But of all those hundreds of fjords to visit, Geiranger Fjord is probably the most incredible.', 62.098102, 7.200183, 40, 3, 20000, 4.5, 0),
(142, 'Sossusvlei', 'Namibia', 'Namibia', 'https://images.pexels.com/photos/5125153/pexels-photo-5125153.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Sossusvlei is undeniably one of the best vacation spots in Nambia.It is a clay and salt pan located within the Namib-Naukluft National Park.', -24.748318, 15.293387, 35, 4, 50000, 3.7, 0),
(143, 'Angkor Wat', 'Cambodia', 'Cambodia', 'https://images.pexels.com/photos/5769435/pexels-photo-5769435.jpeg?auto=compress&cs=tinysrgb&w=400', 'If you love history and archaeology, Angkor Wat is one of the best places to travel in the world.Across 400 square kilometers, this temple of the Hindu faith was built in the 12th century under the Khmer Empire and took a whopping 35 years to complete.', 13.412469, 103.867404, 45, 3, 10000, 4.8, 0),
(144, 'Darvaza gas crater', 'Turkmenistan', 'Turkmenistan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Darvasa_gas_crater_panorama.jpg/1024px-Darvasa_gas_crater_panorama.jpg', 'The Darvaza gas crater, popularly also termed as the Door to Hell, is one of those cool places that you just can’t miss.Located in the Karakum Desert, it is thusly named because it is a giant pool of crimson lava that gives off huge waves of steamy heat.', 40.25241, 58.440212, 40, 4, 20000, 5, 0),
(145, 'Iguazu Falls', 'Argentina/Brazil', 'Argentina/Brazil', 'https://images.pexels.com/photos/3672776/pexels-photo-3672776.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Iguazu Falls isn’t just one single waterfall – it’s a collection of multiple small ones spanning across 3 kilometers, each one cascading down onto the next with raw power and energy that is spectacular to behold.This shocking spectacle alone easily makes this location rank among the top vacation spots in the world.', -25.695276, -54.436637, 45, 3, 300000, 3.9, 0),
(146, 'Tikal', 'Guatemala', 'Guatemala', 'https://images.pexels.com/photos/15124060/pexels-photo-15124060.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Tikal can be found within the thick rainforest of Tikal National Park, and it is a UNESCO world heritage site.The ruins are archaeological wonders that speak of ancient Mayan culture, and it was once a teeming city occupied between the 6th century BC and the 10th century AD.', 17.224355, -89.611766, 50, 6, 50000, 4.4, 0),
(147, 'The Great Blue Hole', 'Belize', 'Belize', 'https://images.pexels.com/photos/2825239/pexels-photo-2825239.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Great Blue Hole may be an odd name to find among the best places to visit, but this sinkhole isn’t just any old lake!It measures 407 feet in depth and spans across 980 feet in width, and it’s so large that you can spot it beautifully from above.', 17.305381, -87.534369, 40, 4, 400000, 4.3, 0),
(148, 'Zhangye Danxia', 'China', 'China', 'https://images.pexels.com/photos/7908325/pexels-photo-7908325.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'At first glance, Zhangye Danxia looks like it may be photoshopped.\nBut it’s all natural, and that’s why these Rainbow Mountains are one of the best places to vacation for unique and breathtaking sights.\nThese mountains make up a geopark and have multicolored stripes, showing off vibrant shades of yellow, red, green, and more.', 39.173424, 100.23431, 35, 5, 60000, 4, 0),
(149, 'Vatnajokull Ice Caves', 'Iceland', 'Iceland', 'https://images.pexels.com/photos/4375346/pexels-photo-4375346.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Vatnajokull Ice Caves are deadly when the ice melts in the spring and summer, but come winter, it’s a tourist’s paradise.A huge network of caverns, tunnels, and caves appear surreal and breathtaking, reflected in bright teal and cerulean thanks to air bubbles, icebergs, and other factors.\n\n', 64.727386, -17.3122, 25, 6, 10000, 3.9, 0),
(150, 'Antelope Canyon', 'USA', 'USA', 'https://images.pexels.com/photos/33041/antelope-canyon-lower-canyon-arizona.jpg?auto=compress&cs=tinysrgb&w=400', 'This geological phenomenon is located on Navajo territory and it is a slot canyon that boasts the privilege of being the most photographed of its kind universally.The upper canyon area is more popular and offers a fantastic view of the curving, wavy walls of sandstone, while the lower canyon area boasts a more up-close-and-personal interaction with the magnolias colors it boasts.', 36.896721, -111.40962, 40, 4, 20000, 5, 0),
(151, 'Lake Bled', 'Slovenia', 'Slovenia', 'https://images.pexels.com/photos/3214968/pexels-photo-3214968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Lake Bled looks like it came out of a medieval movie featuring brave knights and feisty dragons.That’s what makes it so compelling among places to go on vacation.', 46.363912, 14.090068, 35, 5, 13333, 3.4, 0),
(152, 'Pyramids of Giza', 'Egypt', 'Egypt', 'https://images.pexels.com/photos/3185480/pexels-photo-3185480.jpeg?auto=compress&cs=tinysrgb&w=400', 'Most people would consider the world-famous Pyramids of Giza to be among the best vacation spots that the world has to offer.Experience the wonders of ancient Egypt within these pyramids, where you will see sarcophagi, passages, statues, and structures all worthy of exploration.', 29.97916, 31.13339, 25, 6, 55555, 4.1, 0),
(153, 'Mount Fuji', 'Japan', 'Japan', 'https://images.pexels.com/photos/1108701/pexels-photo-1108701.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'For the mountaineers, Mount Fuji is one of the best places to travel in the world.It scales 12,388 feet in height and its beauty is worthy of any storybook cover', 35.36038, 138.72835, 30, 3, 70005, 4.2, 0),
(154, 'Kuang Si Falls', 'Laos', 'Laos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Kuang_Si_Falls_and_a_turquoise_water_pool_in_Luang_Prabang_province_Laos.jpg/1024px-Kuang_Si_Falls_and_a_turquoise_water_pool_in_Luang_Prabang_province_Laos.jpg', 'The Kuang Si Falls is known to be among the top travel destinations for backpackersLocated very close to bustling city Luang Prabang, these waterfalls rush downwards in amazingly clear azure streams, falling through three tiers.', 19.749498, 101.991911, 30, 4, 600500, 4.4, 0),
(155, 'The Great Wall of China', 'China', 'China', 'https://images.pexels.com/photos/4445240/pexels-photo-4445240.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'We can’t talk about the greatest vacation spots in the world without mentioning The Great Wall of China.It covers thousands of miles and sits on top of a mountain, allowing tourists who walk along it to glimpse breathtaking views as far as the eye can see.', 40.431911, 116.57036, 40, 2, 255555, 4.5, 0),
(156, 'Fiordland National Park', 'New Zealand', 'New Zealand', 'https://images.pexels.com/photos/14375108/pexels-photo-14375108.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'If you like nature and culture all in one, New Zealand is one of the best countries to visit.Case in point: the Fiordland National Park.This park holds 14 fjords that, according to Maori legends, were all carved by a giant stonemason with an adze.', -45.462948, 167.542211, 40, 4, 233333, 3.7, 0),
(157, 'Boracay', 'Philippines', 'Philippines', 'https://images.pexels.com/photos/11686040/pexels-photo-11686040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Boracay is among the best places to visit for a relaxing beach trip and some fun in the sun.It’s one of the world’s favorite vacation islands, and its beauty is stunning in its simplicity.', 11.968527, 121.925427, 35, 6, 455555, 4.8, 0),
(158, 'Ik Kil Cenote', 'Mexico', 'Mexico', 'https://images.pexels.com/photos/3822133/pexels-photo-3822133.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Ik Kil Cenote is a natural pit that formed when a cave collapsed back in ancient times.Back then, it was used by Mayans for ritual practices and also for relaxation.\n\n', 20.661054, -88.55121, 40, 3, 100000, 5, 0),
(159, 'The Pitons', 'St. Lucia', 'St. Lucia', 'https://images.pexels.com/photos/12652335/pexels-photo-12652335.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Pitons are a pair of volcanic plugs that go by the names Petit Piton (the smaller one) and Gros Piton (the larger one).Their peaks are striking in appearance and make for incredible landmarks.', 13.803129, -61.066706, 40, 7, 80000, 3.9, 0),
(160, 'Neelum Valley', 'Pakistan', 'Pakistan', 'https://images.pexels.com/photos/1454405/pexels-photo-1454405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Neelum Valley is one of the best places to travel for a more peaceful, calming experience.Its valley, shaped somewhat like a bow, can be found at a 2000-foot altitude in the country’s Azad Kashmir.', 34.598564, 73.907906, 45, 8, 90000, 5, 0),
(161, 'Batu Caves', 'Malaysia', 'Malaysia', 'https://images.pexels.com/photos/3731615/pexels-photo-3731615.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Malaysia isn’t always thought of when you consider the best places to visit in the world, but this old temple cave (alongside other attractions) makes it worth the journey.In 1859, Batu Caves was first discovered on the top of a limestone hill.', 3.240226, 101.685693, 30, 9, 70000, 4.9, 0),
(162, 'Pamukkale Thermal Pools', 'Turkey', 'Turkey', 'https://images.pexels.com/photos/14440071/pexels-photo-14440071.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Pamukkale Thermal Pools are undoubtedly one of the best vacation spots in the nation.Completely natural in structure, these pools are layered over one another thanks to mineral formations and travertines.', 37.923311, 29.122314, 45, 12, 600000, 4.8, 0),
(163, 'Yellowstone National Park', 'Wyoming', 'US', 'https://images.pexels.com/photos/2416600/pexels-photo-2416600.jpeg?auto=compress&cs=tinysrgb&w=400', 'Yellowstone National Park is a breathtaking paradise for those who love the outdoors.Spanning almost 3,500 square miles, this park is a trove of steep canyons, incredible mountains, gorgeous waterfalls, and fascinating geysers', 44.981054, -110.710514, 30, 5, 705045, 4.6, 1),
(164, 'Maroon Bells', 'Colorado', 'US', 'https://www.aspensnowmass.com/-/media/aspen-snowmass/images/hero/hero-image/winter/2021-22/maroon-bells-hero-07202021.jpg?mw=752&mh=464&hash=4649481E6A73BE76A4BD26EB5D25ECED', 'Aspen, Colorado is home to the stunning and gorgeous Maroon Bells, which earn their name from the majestic appearance cast by two peaks of the Rocky Mountains.', 39.070913, -106.988755, 45, 6, 700000, 4.2, 0),
(165, 'Watkins Glen State Park', 'NewYork', 'US', 'https://images.pexels.com/photos/14006846/pexels-photo-14006846.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Watkins Glen State Park is located in upstate New York, within the Finger Lakes area, and it is named after the nearest town.It may be relatively small compared to many more famous parks at 778 acres, but it is home to a gorge that holds a grand total of 19 gorgeous waterfalls.', 42.38981631, -76.85909159, 30, 4, 70500, 4.7, 0),
(166, 'Monument Valley', 'Arizona/Utah', 'US', 'https://images.pexels.com/photos/161820/monument-valley-west-western-161820.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Monument Valley is a minimalist attraction located along the border of Utah and Arizona.In spite of its simplicity, this red-sand desert may just be one of the most beautiful places you will ever see!', 36.996895, -110.098617, 65, 6, 600000, 4.6, 0),
(167, 'Crater Lake', 'Oregon', 'US', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Crater_Lake_winter_pano2.jpg/1024px-Crater_Lake_winter_pano2.jpg', 'Crater Lake is an arresting body of magnificent blue water that rests peacefully within Mount Mazama.Spanning 53 square kilometers and 2000 feet deep, this incredible caldera was left behind after an explosion more than 7 millennia ago.', 42.938644, -122.091827, 50, 7, 200000, 3.7, 0),
(168, 'Niagara Falls', 'NewYork', 'US', 'https://images.pexels.com/photos/1374585/pexels-photo-1374585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'New York is home to many amazing attractions, but Niagara Falls is arguably one of those that everyone will tell you not to miss.It’s right on the border between the USA and Canada, and it’s a must-see attraction, for sure.', 43.089481, -79.084924, 50, 6, 355550, 4.4, 0),
(169, 'Death Valley National Park', 'California', 'US', 'https://images.pexels.com/photos/226365/pexels-photo-226365.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'You wouldn’t think that a basin called “Death Valley” would be one of the most beautiful places in the US.After all, it is located below sea level, and it is easily the hottest and driest spot in all of America.', 36.72528985, -116.9779806, 42, 9, 10000, 4.3, 0),
(170, 'Blue Ridge Parkway', 'North Carolina/Virginia', 'US', 'https://www.gannett-cdn.com/-mm-/4f453862e206797cc203cf69f5563e09aaec8a54/c=0-108-2122-1307/local/-/media/2016/03/08/USATODAY/USATODAY/635930385504268911-northcarolina-blueridgeparkway.jpg?width=660&height=373&fit=crop&format=pjpg&auto=webp', 'The Blue Ridge Parkway is a highway, which may surprise you, as most roads can’t be considered beautiful places.But this highway spans 469 miles in length, over multiple countries throughout North Carolina and Virginia, and offers some of the most spectacular views in the country.', 36.569348, -80.90787, 40, 8, 20000, 4, 0),
(171, 'Kenai Fjords', 'Alaska', 'US', 'https://images.pexels.com/photos/10304564/pexels-photo-10304564.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Kenai Fjords are largely taken up by an impressive forty shining glaciers that easily swarf their surroundings.They make for what might just be the most dazzling fjord in all of the United States – and it’s fitting that they would be in Alaska!', 59.848188, -150.188007, 35, 7, 50000, 3.9, 0),
(172, 'Savannah', 'Georgia', 'US', 'https://images.pexels.com/photos/259411/pexels-photo-259411.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Savannah is an old city that is home to multiple fascinating sites.Its streets are paved with cobblestones and flanked by old buildings like museums and churches that are simply stuffed with history.', 32.08056, -81.091563, 45, 6, 10000, 5, 0),
(173, 'Philadelphia', 'Pennsylvania', 'US', 'https://images.pexels.com/photos/6379145/pexels-photo-6379145.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Love history? Philadelphia is the place for you!It may not be the typical idea of the most beautiful places, but it is the only city in all of America to be named a UNESCO World Heritage city.', 39.949719, -75.168772, 40, 4, 20000, 3.4, 0),
(174, 'Turnip Rock', 'Michigan', 'US', 'https://www.mlive.com/resizer/b8kq-r_IsM7SNloC_CQQZFsKPg8=/500x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.mlive.com/home/mlive-media/width2048/img/travel_impact/photo/23405140-standard.jpg', 'Turnip Rock isn’t exactly the most famous of attractions in the United States, but that’s due to lack of knowledge, not lack of magnificence.It’s a very small island that you can spot from Lake Huron’s shorelines in Port Austin, Michigan.', 44.06834239, -82.95907486, 45, 5, 300000, 4.1, 0),
(175, 'Badlands National Park', 'South Dakota', 'US', 'https://images.pexels.com/photos/13195552/pexels-photo-13195552.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Badlands National Park located in South Dakota may sound foreboding, but in reality, it’s one of the most beautiful places in the US.It is famous for holding an extremely rich and diverse fossil bed that is definitely one of the best that earth has to offer.', 43.855326, -102.339728, 50, 3, 50000, 4.2, 0),
(176, 'Willow City Bluebonnets', 'Texas', 'US', 'https://traveladdicts.net/wp-content/uploads/2021/11/Texas-bluebonnets-Willow-City-Loop-960x640.jpg.webp', 'If you love wildflowers, head down to Texas Hill Country to feast your eyes upon the delightful expanses of bright Bluebonnets along Willow City Loop in Gillespie County.They bloom in full force every April, and you can walk along a designated Bluebonnet trail to truly get the most out of this special floral occurrence.', 30.400745, -98.701425, 40, 4, 400000, 4.4, 0),
(177, 'Kauai', 'Hawaii', 'US', 'https://images.pexels.com/photos/2521619/pexels-photo-2521619.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'Kauai looks like a place right out of a fantasy book. It is an island paradise that is the oldest of all habited Hawaiian islands.It home to such beautiful wonders as the 6,175-acre Nā Pali Coast State Park, which is packed with hiking trails, emerald green mountains, and stunning views, and the 173-foot high Wailua Falls.', 22.095412, -159.52829, 35, 5, 60000, 4.5, 0),
(178, 'Glacier National Park', 'Montana', 'US', 'https://images.pexels.com/photos/2589456/pexels-photo-2589456.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 'The Glacier National Park located in Montana provides some of the most incredible views that you’ll be privy to in America.It sits neatly on the border between Canada and the US, and it is exceedingly large in size, spanning more than 1 million acres in total.', 48.76099671, -113.7875063, 25, 9, 10000, 3.7, 0),
(179, 'White Sands National Monument', 'Mexico', 'US', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Aerial_view_of_dunefield%2C_White_Sands_National_Park%2C_New_Mexico%2C_United_States.png/1024px-Aerial_view_of_dunefield%2C_White_Sands_National_Park%2C_New_Mexico%2C_United_States.png', 'This incredibly unique location can be found in the north of the Chihuahuan Desert.The White Sands National Monument consists of a reaching, widespread expanse of white gypsum crystal sand dunes, backdropped by a picturesque blue sky.', 32.786947, -106.32594, 40, 7, 20000, 4.8, 0),
(180, 'Great Smoky Mountains National Park', 'Tennessee', 'US', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/View_atop_Cliff_Tops_on_Mount_LeConte%2C_GSMNP%2C_TN.jpg/1024px-View_atop_Cliff_Tops_on_Mount_LeConte%2C_GSMNP%2C_TN.jpg', 'There are plenty of reasons to visit the gorgeous Great Smoky Mountains National Park, which sits on the Tennessee and North Carolina border.It is packed with hiking routes ripe with emerald greenery, waterfalls and bodies of water, and pretty wildflowers ready for photos.', 35.613023, -83.553203, 35, 5, 13333, 5, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `purchased_packages`
--
ALTER TABLE `purchased_packages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `register_user_details`
--
ALTER TABLE `register_user_details`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tourist_places`
--
ALTER TABLE `tourist_places`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `purchased_packages`
--
ALTER TABLE `purchased_packages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `register_user_details`
--
ALTER TABLE `register_user_details`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `tourist_places`
--
ALTER TABLE `tourist_places`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=181;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
